services:
  api:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=sqlite:///./database.sqlite

  vue:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
